# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.GithubRepoStarsCountPlugin}}
plugins:
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - chat2way/ZMarkupParser
      - chat2way/ZReviewTender
      - chat2way/ZMediumToMarkdown
      - chat2way/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "chat2way's Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "@chat2way"

# Tagline section text
tagline: >-
    A software engineer who loves playing piano and accordion.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-house-chimney"
      text: "KSCC"
      url: "https://kscc.ksyun.ai"
      alt: "KSCC's Website"
      title: "KSCC's Website"
      target: "_blank"
  - link:
      icon: "fa-brands fa-twitter"
      text: "X(Twitter)"
      url: "https://x.com/chat2way"
      alt: "Chat2Way on X."
      title: "Chat2Way on X."
      target: "_blank"
  - link:
      icon: "fa-brands fa-square-github"
      text: "Github"
      url: "https://github.com/chat2way"
      alt: "Chat2Way on GitHub Pages."
      title: "Chat2Way on GitHub Pages."
      target: "_blank"
  - link:
      icon: "fa-brands fa-instagram"
      text: "Instagram"
      url: "https://www.instagram.com/chat2way"
      alt: "Chat2Way on Instagram."
      title: "Chat2Way on Instagram."
      target: "_blank"
  - link:
      icon: "fa-solid fa-envelope"
      text: "Email"
      url: "mailto:chat2way@gmail.com"
      alt: "chat2way@gmail.com"
      title: "Email: chat2way@gmail.com"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame

# Footer text
footer: >
    Hi there! Follow me on X or GitHub, or stay connected on Instagram.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2026 Chat2Way
